import React from 'react'
export const messageList =[
    {   
        id:1,
        username: "bot",
        content:" Jai Jinendra! We, Jains's & Daglia's have great news to share with you!",
        buttonText:" Jai Jinendra! We, Jains's & Daglia's have great news to share with you!",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {   
        id:2,
        username: "bot",
        content: <p><b>Tap below</b> to know more!👇🏼</p>,
        buttonText: <p><b>Tap below</b> to know more!👇🏼</p>,
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    }, 
    {
        id:3,
        username: "user",
        content: 'I am interested to know…',
        buttonText: 'I am interested to know…',
        type:'text',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        display:false,
    }, 
    {
        id:4,
        username: "bot",
        content: '',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        image:require('../images/third.jpeg'),
        display:false,
    }, 
        {
        id:5,
        username: "bot",
        content: <p><b>Rohan & Prashansa</b> are tying the knot!</p> ,
        buttonText: <p><b>Rohan & Prashansa</b> are tying the knot!</p> ,
        img: "http://i.imgur.com/ARbQZix.jpg",
        type:'text',

        display:false,
    }, 
    {
        id:6,
        username: "bot",
        content: <p>And you’re invited for the <b>BIG FAT INDIAN WEDDING!</b></p>,
        buttonText: <p>And you’re invited for the <b>BIG FAT INDIAN WEDDING!</b></p>,
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    }, 
    {
        id:7,
        username: "user",
        content: ' Congratulations! 💃💃  What are the dates?',
        buttonText: ' Congratulations! 💃💃  What are the dates?',
        type:'text',
        display:false,
    }, 
        {
            id:8,
            username: "bot",
            content: '18th - 20th December, 2022',
            buttonText: '18th - 20th December, 2022',
            img: "http://i.imgur.com/Tj5DGiO.jpg",
            type:'text',
            display:false,
        },
        {
        id:9,
        username: "bot",
        content: "It's a destination wedding, held at Raajsa Resort, Kumbalgargh, Rajhastan.",
        buttonText: 'Awesome! Where are the events?',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    //     {
    //     id:10,
    //     username: "bot",
    //     content: '',
    //     img: "http://i.imgur.com/Tj5DGiO.jpg",
    //     image:require('../images/hotel.avif'),
    //     type:'image ',
    //     display:false,
    // },
    {
        id:10,
        username: "bot",
        content: '',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        image:require('../images/hotel.jpeg'),
        display:false,
    },
    {
        id:11,
        username: "user",
        content: ' That’s awesome! Excited for a destination wedding 😃',
        buttonText: 'That’s awesome!😃',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:12,
        username: "bot",
        content: 'On 18th December, we have Baraat Swagat followed by Welcome Dinner from 5:30 PM onwards.',
        buttonText: 'On 18th December, we have Baraat Swagat followed by Welcome Dinner from 5:30 PM onwards.',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:13,
        username: "user",
        content:'Sounds good!',
        buttonText:'Sounds good!',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },  
    {
        id:14,
        username: "bot",
        content: 'on 19th December,',
        buttonText: 'on 19th December,',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:15,
        username: "bot",
        content: 
        <p>We have Mahera in the afternoon,<br></br>
        - Grooms Side at <strong>10:15 AM</strong>,<br/> 
        - Bride's Side at  <strong>11:00 AM</strong>
        </p>,
        buttonText: 'We have Mahera in the afternoon.',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:16,
        username: "bot",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        // image:'https://scontent.fbom19-1.fna.fbcdn.net/v/t31.0-8/26756734_10155893614176142_5426006532846277824_o.jpg?_nc_cat=108&_nc_ht=scontent.fbom19-1.fna&oh=3ae7dfd59a8061f4daa18ae485dc3e96&oe=5D26F719',
        type:'text',
        content:'Followed by Sangeet in the evening at 6:15 PM',
        display:false,
    },  
    // Dancing Gif
    {
        id:17,
        username: "bot",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        image:require('../images/SANGEET.gif'),
        type:'image',
        display:false,
    },
    {
        id:18,
        username: "user",
        content:"That's going to be Fun!",
        buttonText:"That's going to be Fun!",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    }, 
    {
        id:19,
        username: "bot",
        content: 'On 20th December, we have Carnival in the morning at 10:00 AM…',
        buttonText: 'On 20th December, we have Carnival in the morning at 10:00 AM…',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    // carnival Gif
    {
        id:20,
        username: "bot",
        image:require('../images/carnival.gif'),
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        display:false,
    },
    {
        id:21,
        username: "bot",
        content: 'Nikasi in the afteroon at 3:15 PM 🕺 💃',
        buttonText: 'Nikasi in the afteroon at 3:15 PM 🕺 💃',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    // Nikasi GIF
    {
        id:22,
        username: "bot",
        image:require('../images/Nikasi.gif'),
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        display:false,
    },
    {
        id:23,
        username: "bot",
        content: 'Followed by Varmala & Phera at 05:00 PM ❤️❤️',
        buttonText: 'Followed by Varmala & Phera at 05:00 PM (Heart Emoji)',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    // Phera GIF!
    {
        id:24,
        username: "bot",
        image:require('../images/Phera.gif'),
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        display:false,
    },
    {
        id:25,
        username: "user",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        content:"It's going to be a dream wedding!",
        buttonText:"It's going to be a dream wedding!",
        display:false,
    },
    // Cheers Gif
    {
        id:26,
        username: "user",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        image:require('../images/awesome.gif'),
        type:'image',
        display:false,
    },
    {
        id:27,
        username: "bot",
        content: <p>We are so excited to see you for our wedding. Hope to see you there!</p>,
        buttonText: <p>Get set for<b> #AdiSnehDaVyaah</b>, we’ll see you there !</p>,
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    // Couple Photo
    {
        id:28,
        username: "bot",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        image:require('../images/second.jpeg'),
        display:false,
    },
    {
        id:29,
        username: "user",
        content: "Surely, we'll let you know..",
        buttonText: "Surely, we'll let you know..",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:30,
        username: "bot",
        content:<p> <a style={{display: "table-cell"}} href="https://drive.google.com/file/d/1PJF8gmzV4XP67rBfilJYiOuRdqeqEK42/view?usp=share_link" target="_blank" download={true}>click here (Invite link)</a></p>
        ,
        buttonText: 'Oh and RSVP with your name at the link below please?',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:31,
        username: "bot",
        content: <p>Kindly RSVP with your name at the link below.<br/> <br/>
                 <p> <a style={{display: "table-cell"}} href="https://forms.gle/Y8GWz8jzB7xdbxGUA" target="_blank">RSVP link</a></p></p>            
        ,
        buttonText: 'Oh and RSVP with your name at the link below.?',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:32,
        username: "bot",
        // And also don’t forget to use #terenaalPRhogaya while posting selfies on social media
        content: <p>And also don’t forget to use <strong>#terenaalPRhogaya</strong> while posting selfies on social media.</p>,
        buttonText: 'Thank you! So excited to see you there!',
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'text',
        display:false,
    },
    {
        id:33,
        username: "bot",
        img: "http://i.imgur.com/Tj5DGiO.jpg",
        type:'image',
        image:require('../images/selfies.gif'),
        display:false,
    },   
];
